### ISSUE TITLE
Code example for ItemizeList and EnumerateList

### ISSUE THREAD

**Issue by iamit06** [xatkit-bot-platform/xatkit-react-platform#17]
Hi, I wanted to use ItemizeList and EnumerateList, but could not use rightly and getting errors. Please provide some code example to use them properly.
Regards

**Comment by gdaniel** [comment]
Hi, what are the errors you get?

**Comment by iamit06** [comment]
Hi Daniel, I am trying to change GreetingsBot React example for ItemizeList like below
HandleListOption {
	Body {
		ChatPlatform.ItemizeList(["Yes","No"])
	}
	Next {
		_ --> Init
	}
}
So I think I am not doing it correctly so getting exception. Please suggest how to use ItemizeList in this example. I also referred  documentation but not able to understand.
Thanks

**Comment by iamit06** [comment]
Hi Daniel,
With above code changes I am getting below error:
[ERROR] 06:21:05,991 - No endpoint registered for GET: /favicon.ico
[INFO]  06:21:09,897 - XatkitSession 3b20b5c4-7d94-4ff1-8d3f-f1f85d4d6df3 created
[INFO]  06:21:10,011 - Detected Intent Welcome (confidence 1) from query text "Hi" (Session=3b20b5c4-7d94-4ff1-8d3f-f1f85d4d6df3)
[ERROR] 06:21:10,037 - An error occurred when executing fallback of state HandleWelcome
java.lang.ClassNotFoundException: ChatPlatform
	at java.net.URLClassLoader.findClass(URLClassLoader.java:381)
	at java.lang.ClassLoader.loadClass(ClassLoader.java:424)
	at sun.misc.Launcher$AppClassLoader.loadClass(Launcher.java:331)
	at java.lang.ClassLoader.loadClass(ClassLoader.java:357)
	at java.lang.Class.forName0(Native Method)
	at java.lang.Class.forName(Class.java:348)
	at org.eclipse.xtext.common.types.access.impl.ClassFinder.forName(ClassFinder.java:41)
	at org.eclipse.xtext.common.types.access.impl.ClassFinder.forName(ClassFinder.java:15)
	at org.eclipse.xtext.common.types.access.impl.AbstractClassFinder.forName(AbstractClassFinder.java:43)
	at org.eclipse.xtext.xbase.interpreter.impl.XbaseInterpreter.translateJvmTypeToResult(XbaseInterpreter.java:781)
	at org.eclipse.xtext.xbase.interpreter.impl.XbaseInterpreter._doEvaluate(XbaseInterpreter.java:862)
	at org.eclipse.xtext.xbase.interpreter.impl.XbaseInterpreter.doEvaluate(XbaseInterpreter.java:224)
	at com.xatkit.core.ExecutionService.doEvaluate(ExecutionService.java:477)
	at org.eclipse.xtext.xbase.interpreter.impl.XbaseInterpreter.internalEvaluate(XbaseInterpreter.java:204)
	at org.eclipse.xtext.xbase.interpreter.impl.XbaseInterpreter._doEvaluate(XbaseInterpreter.java:768)
	at org.eclipse.xtext.xbase.interpreter.impl.XbaseInterpreter.doEvaluate(XbaseInterpreter.java:220)
	at com.xatkit.core.ExecutionService.doEvaluate(ExecutionService.java:477)
	at org.eclipse.xtext.xbase.interpreter.impl.XbaseInterpreter.internalEvaluate(XbaseInterpreter.java:204)
	at org.eclipse.xtext.xbase.interpreter.impl.XbaseInterpreter._doEvaluate(XbaseInterpreter.java:447)
	at org.eclipse.xtext.xbase.interpreter.impl.XbaseInterpreter.doEvaluate(XbaseInterpreter.java:228)
	at com.xatkit.core.ExecutionService.doEvaluate(ExecutionService.java:477)
	at org.eclipse.xtext.xbase.interpreter.impl.XbaseInterpreter.internalEvaluate(XbaseInterpreter.java:204)
	at org.eclipse.xtext.xbase.interpreter.impl.XbaseInterpreter.evaluate(XbaseInterpreter.java:190)
	at com.xatkit.core.ExecutionService.executeBody(ExecutionService.java:193)
	at com.xatkit.core.ExecutionService.lambda$handleEventInstance$0(ExecutionService.java:399)
	at java.util.concurrent.CompletableFuture$AsyncRun.run(CompletableFuture.java:1626)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
	at java.lang.Thread.run(Thread.java:745)

Please suggest.

**Comment by gdaniel** [comment]
Hi,

From [the docs](https://github.com/xatkit-bot-platform/xatkit/wiki/Xatkit-Chat-Platform): `ChatPlatform` does provide an `ItemizeList` action, if you want to use it you need to call it on the `ReactPlatform`, example below.

```
MyState {
  Body {
    var itemizedList = ReactPlatform.ItemizeList(#["A", "B"])
    ReactPlatform.Reply(itemizedList)
  }
  Next [...]
}
```

As explained in the [ReactPlatform Documentation](https://github.com/xatkit-bot-platform/xatkit/wiki/Xatkit-React-Platform): `ItemizeList` returns a `String`, if you want to display it to the end user you need to use it in a `Reply` or `PostMessage` action. 

Gwendal

**Comment by iamit06** [comment]
Thanks Daniel, with your code suggestion its working now.
